lang = "TS"
organization_id = "ginger-society"
dir = "src/services"
refs_file = "src/shared/references.ts"
service_type = "Portal"

[services."@ginger-society/IAMService"]
stage_k8 = "http://iam-service-api-service/iam"
prod_k8 = "http://iam-service-api-service/iam"
stage = "https://api-staging.gingersociety.org/iam"
dev = "http://localhost:8080/iam"
prod = "https://api.gingersociety.org/iam"

[portals_refs]

[ws_refs."@ginger-society/IAMService"]
stage = ""
stage_k8 = ""
dev = ""
prod = ""
prod_k8 = ""

[urls]
stage = "https://iam-staging.gingersociety.org"
dev = "http://localhost:3001"
prod = "https://iam.gingersociety.org"

[urls_ws]
