dir = "src/services"
lang = "TS"
organization_id = "ginger-society"
refs_file = "src/shared/references.ts"
service_type = "Portal"

[services."@ginger-society/IAMService"]
dev = "http://localhost:8080/iam"
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[portals_refs]

[urls]
dev = "http://localhost:3001"
stage = "https://iam-staging.gingersociety.org"

[urls_ws]
